# Generated by Django 5.2.7 on 2025-10-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('prompt_templates', '0001_initial'),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_prompts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='prompts.prompt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_templates',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='prompt_templates.prompttemplate'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=650),
        ),
    ]
